server:
  port: 8020

spring:
  thymeleaf:
    cache: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:h2:./test_dev;MODE=MySQL
    driverClassName: org.h2.Driver
    username: sa
    password: